name: Magic

on:
  schedule:
    # 4:00 i 14:00 UTC to ok. 6:00 i 16:00 w Polsce
    - cron: '0 4,14 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install pandas requests tqdm

      - run: python main.py

      - name: Commit CSV
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add final_boss.csv
          git commit -m "update" || echo "no changes"
          git push
